services:
  qinglong:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-ghcr.io/whyour/qinglong:debian}
        QINGLONG_VERSION: ${QINGLONG_VER:-unknown}
    image: qinglong-playwright:latest
    container_name: qinglong
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5700:5700"
    volumes:
      - data:/ql/data
      # - "${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa:ro"
      # - "${HOME}/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro"

volumes:
  data:
